# Generated by Django 5.2.8 on 2025-12-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_rename_home_issued_student_ret_idx_home_issued_student_134c07_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload student ID card with clear face photo', upload_to='id_cards/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='home.student')),
            ],
            options={
                'verbose_name': 'ID Card',
                'verbose_name_plural': 'ID Cards',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_data', models.BinaryField(help_text='128-dimensional face encoding vector')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Quality score of the face encoding (0-1)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active encodings are used for recognition')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='home.student')),
                ('id_card', models.ForeignKey(blank=True, help_text='Source ID card for this encoding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_encodings', to='idchartrecognation.idcard')),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='idchartreco_student_c2edcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recognition_logs/')),
                ('result', models.CharField(choices=[('success', 'Success'), ('no_match', 'No Match Found'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('poor_quality', 'Poor Quality Image'), ('error', 'Error')], max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='Match confidence score (lower is better, < 0.6 is good match)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='Additional details or error messages')),
                ('matched_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to='home.student')),
            ],
            options={
                'verbose_name': 'Recognition Log',
                'verbose_name_plural': 'Recognition Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idchartreco_timesta_ee332e_idx'), models.Index(fields=['matched_student', '-timestamp'], name='idchartreco_matched_8fa6fa_idx')],
            },
        ),
    ]
