# Generated by Django 5.2.8 on 2025-12-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_backend_improvements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='issuedbook',
            new_name='home_issued_student_134c07_idx',
            old_name='home_issued_student_ret_idx',
        ),
        migrations.RenameIndex(
            model_name='issuedbook',
            new_name='home_issued_book_id_fd63ec_idx',
            old_name='home_issued_book_ret_idx',
        ),
        migrations.RenameIndex(
            model_name='issuedbook',
            new_name='home_issued_expiry__437f3c_idx',
            old_name='home_issued_expiry_idx',
        ),
    ]
